import numpy as np
import cv2

triangle = np.zeros((300, 300), dtype="uint8")
points = np.array([[0, 300], [150, 0], [300, 300]], np.int32)
points = points.reshape((-1, 1, 2))

cv2.polylines(triangle, [points], isClosed=True, color=(255, 255, 255), thickness=2)
cv2.fillPoly(triangle, [points], color=(255, 255, 255))
cv2.imshow("Trojkat", triangle)

circle = np.zeros((300, 300), dtype = "uint8")
cv2.circle(circle, (150, 150), 150, 255, -1)
cv2.imshow("Circle", circle)
bitwiseAnd = cv2.bitwise_and(triangle, circle)
cv2.imshow("AND", bitwiseAnd)
cv2.waitKey(0)
cv2.destroyWindow("AND")
bitwiseOr = cv2.bitwise_or(triangle, circle)
cv2.imshow("OR", bitwiseOr)
cv2.waitKey(0)
cv2.destroyWindow("OR")
bitwiseXor = cv2.bitwise_xor(triangle, circle)
cv2.imshow("XOR", bitwiseXor)
cv2.waitKey(0)
cv2.destroyWindow("XOR")
bitwiseNot = cv2.bitwise_not(triangle)
cv2.imshow("NOT triangle", bitwiseNot)
cv2.waitKey(0)
cv2.destroyWindow("NOT triangle")
bitwiseNot = cv2.bitwise_not(circle)
cv2.imshow("NOT circle", bitwiseNot)
cv2.waitKey(0)
cv2.destroyAllWindows()